### ISSUE TITLE
Create the data model for the project

### ISSUE THREAD

**Issue by a-monemian-vineti** [VinetiInternship2021/final-project-URS#1]
Create a basic schema for database (using LucidChart)

**Comment by Lusine0101** [comment]
Here is our data model, please review. 
https://lucid.app/lucidchart/invitations/accept/inv_142602b7-d4df-4849-8639-6a37478418b0

**Comment by a-monemian-vineti** [comment]
I left a couple of comments about some names and types but the more I think about it, I see that separating event booking and room booking would a better call. 
Since booking an event doesn't need starts/ends_at and doesn't affect the availability of rooms, we can put it in a separate table and just have a relation with events.
Then we can book a room and associate an event for it for the professors or a booking with no event at all.
